const express=require("express")
const app=express()
const db=require('./models')
const userRoutes=require('./routers/user-routes')
const productRoutes=require('./routers/product-routes')
const profilRoutes=require('./routers/profil-routes')
app.use(express.urlencoded({extended:true}))
app.use((req,res,next)=>{
    res.setHeader('Access-Control-Allow-Origin','*')
    res.setHeader('Access-Control-Request-Method','*')
    res.setHeader('Access-Control-Allow-Headers','*')
    res.setHeader('Access-Control-Allow-Methods','*')
    next()
  }) 
app.use(express.json())
app.use('/',userRoutes)
app.use('/',productRoutes)
app.use('/',profilRoutes)
db.sequelize.sync().then(()=>{
    app.listen(4040,()=>console.log("server listening in port 4040"))
})